services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: ["uv", "run", "--no-dev", "--directory", "api", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - ALLOWED_GITHUB_USERS=${ALLOWED_GITHUB_USERS}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app/api
          ignore:
            - .venv/
            - __pycache__/
            - .ruff_cache/
            - "*.pyc"
            - README.md
        - action: rebuild
          path: ./api/pyproject.toml

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./bot
          target: /app/bot
          ignore:
            - .venv/
            - __pycache__/
            - .ruff_cache/
            - "*.pyc"
            - README.md
        - action: rebuild
          path: ./bot/pyproject.toml
