[project]
name = "api"
version = "0.1.0"
description = "Trading Bot API Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "redis>=5.0.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.12.12",
]
